// <auto-generated />
namespace ShelbyChester.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ContainerRentTest5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContainerRentTest5));
        
        string IMigrationMetadata.Id
        {
            get { return "202206050305418_ContainerRentTest5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
