// <auto-generated />
namespace ShelbyChester.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class basketItemName1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(basketItemName1));
        
        string IMigrationMetadata.Id
        {
            get { return "202206050314382_basketItemName1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
